<?php
namespace frontend\controllers;

use app\models\Octo;
use app\models\Transactions;
use common\models\Slider;
use dvizh\order\controllers\OrderController;
use dvizh\order\Order;
use dvizh\shop\models\Producer;
use Yii;
use yii\data\ActiveDataProvider;
use yii\filters\VerbFilter;
use yii\helpers\Json;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use dvizh\shop\models\Category;
use frontend\models\ContactForm;
use common\models\dvizh\Product;
use yii\web\NotFoundHttpException;

/**
 * Site controller
 */
class SiteController extends Controller
{

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'notify-payment' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function beforeAction($action)
    {
        if ($action->id === 'notify-payment') {
            $this->enableCsrfValidation = false;
        }

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        $categories = Category::find()->all();
        $sliders = Slider::find()->all();

        $newArrivals = new ActiveDataProvider([
            'query' => Product::find()
                ->where(['available' => 'yes', 'is_new' => 'yes'])
                ->orderBy(['id' => SORT_DESC])  // latest products
                ->limit(12),
            'pagination' => false,
        ]);

        $trending = new ActiveDataProvider([
            'query' => Product::find()
                ->where(['available' => 'yes', 'is_popular' => 'yes'])
                ->orderBy(['id' => SORT_DESC])
                ->limit(12),
            'pagination' => false,
        ]);

        $specials = new ActiveDataProvider([
            'query' => Product::find()
                ->where(['available' => 'yes', 'is_promo' => 'yes'])
                ->orderBy(['id' => SORT_DESC])
                ->limit(12),
            'pagination' => false,
        ]);

        $producers = Producer::find()->all();

        if($catId = yii::$app->request->get('categoryId')) {
            $category = Category::findOne($catId);
        } elseif($categories) {
            $category = current($categories);
        } else {
            $category = null;
        }

        if($category) {
            $query = Product::find()->category($category->id)->orderBy('id DESC');
        } else {
            $query = Product::find()->orderBy('id DESC');
        }

        $queryForFilter = clone $query;

        if($filter = yii::$app->request->get('filter')) {
            $query->filtered($filter);
        }

        $products = $query->limit(12)->all();

        return $this->render('index', [
            'queryForFilter' => $queryForFilter,
            'categories' => $categories,
            'products' => $products,
            'category' => $category,
            'producers' => $producers,
            'sliders' => $sliders,
            'newArrivals' => $newArrivals,
            'trending' => $trending,
            'specials' => $specials,
        ]);
    }

    public function actionThanks($id)
    {
        $model = \dvizh\order\models\Order::findOne(['id' => $id]);
        return $this->render('thanks', [
            'model' => $model
        ]);
    }

    public function actionCheckout(){

        return $this->render('checkout', [

        ]);
    }

    /**
     * Displays contact page.
     *
     * @return mixed
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                Yii::$app->session->setFlash('success', 'Thank you for contacting us. We will respond to you as soon as possible.');
            } else {
                Yii::$app->session->setFlash('error', 'There was an error sending email.');
            }

            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Displays about page.
     *
     * @return mixed
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    public function actionInitPayment($order_id){
        $octo = new Octo();
        $order = \dvizh\order\models\Order::findOne($order_id);
        $request = $octo->PreparePayment($order);
        if($request['status']){
            return $this->redirect($request['url']);
        }else{
            Yii::$app->session->setFlash('error', $request['message']);
            Yii::error(['InitPayment' => $request['message']]);
            return $this->goHome();
        }
    }


    public function actionAcceptPaymentOld($order_id, $transaction_id){
        $order = \dvizh\order\models\Order::findOne($order_id);
        $transaction = Transactions::findOne(["transaction_id" => $transaction_id]);

        $order->setPaymentStatus($transaction->status);

        if ($transaction->status === 'succeeded') {
            $order->setStatus('approve');
        } elseif ($transaction->status === 'cancelled') {
            $order->setStatus('cancel');
            throw new BadRequestHttpException('Payment was Unsuccessful');
        }

        $db = Yii::$app->db;
        $tx = $db->beginTransaction();

        Yii::error(['acceptRequest' => $this->request->getRawBody()]);




        return $this->redirect(['thanks', 'id' => $order_id]);
    }

    public function actionAcceptPayment($order_id, $transaction_id)
    {
        $order = \dvizh\order\models\Order::findOne($order_id);
        $transaction = Transactions::findOne(['transaction_id' => $transaction_id]);

        if (!$order || !$transaction) {
            throw new NotFoundHttpException();
        }

        $db = Yii::$app->db;
        $tx = $db->beginTransaction();

        try {
            $order->setPaymentStatus($transaction->status);

            if ($transaction->status === 'succeeded') {
                $order->setStatus('approve');

                // ---- ODOO INTEGRATION ----
                $lines = [];

                foreach ($order->elements as $element) {
                    $product = $element->item;

                    // Skip products not synced with Odoo
                    if (empty($product->external_id)) {
                        Yii::warning([
                            'order_id'   => $order->id,
                            'product_id' => $product->id,
                            'reason'     => 'Missing Odoo external_id',
                        ], 'app');
                        continue;
                    }

                    $lines[] = [
                        0, 0, [
                            'product_id'      => (int)$product->external_id,
                            'product_uom_qty' => (float)$element->count,
                            'price_unit'      => (float)$element->price,
                        ]
                    ];
                }


                Yii::$app->odoo->createSaleOrder([
                    'partner_id' => $order->user_id,
                    'origin' => 'Order #' . $order->id,
                    'order_line' => $lines,
                ]);
            } elseif ($transaction->status === 'cancelled') {
                $order->setStatus('cancel');
                throw new BadRequestHttpException('Payment was unsuccessful');
            }

            $order->save(false);
            $tx->commit();

        } catch (\Throwable $e) {
            $tx->rollBack();
            Yii::error($e->getMessage(), 'payment');
            throw $e;
        }

        return $this->redirect(['thanks', 'id' => $order_id]);
    }

    public function actionNotifyPayment(){
        Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;

        $octo = new Octo();
        $octo->sendTelegram($this->request->getRawBody());
        $post = Json::decode($this->request->getRawBody());

        Yii::error(['NotifyPayment' => $this->request->getRawBody()]);

        if($post){
            $transaction = Transactions::findOne(["transaction_id" => $post['shop_transaction_id']]);
            if(!$transaction) return false;

            $transaction->status = $post['status'] ?? null;
            $transaction->signature = $post['signature'] ?? null;
            $transaction->hash_key = $post['hash_key'] ?? null;
            $transaction->total_sum = $post['total_sum'] ?? null;
            $transaction->transfer_sum = $post['transfer_sum'] ?? null;
            $transaction->refunded_sum = $post['refunded_sum'] ?? null;
            $transaction->card_country = $post['card_country'] ?? null;
            $transaction->maskedPan = $post['maskedPan'] ?? null;
            $transaction->rrn = $post['rrn'] ?? null;
            $transaction->payed_time = $post['payed_time'] ?? null;
            $transaction->card_type = $post['card_type'] ?? null;
            $transaction->is_physical_card = $post['is_physical_card'] ?? null;
            $transaction->save();
        }

        return true;
    }
}
